-- UI Polish beranda (06 Jul 2026):
-- 1) Modul 480 Galeri Fasilitas: foto asli berbeda per kartu (.facility-thumb)
-- 2) Modul 482 Role Model: kartu HTML (foto polos + nama/jabatan/NIP), bukan poster teks-baked
-- 3) Modul 816 Indeks Pelayanan Publik: tile skor besar SKM/IPAK + lightbox dokumen
--    (skor diinput manual per triwulan — perbarui saat refresh-survey.py mengganti gambar)
-- 4) Modul 810 Lokasi Kami: matikan judul chrome (judul dobel dengan heading di konten)

UPDATE pnn_modules SET content = '<h2>Galeri Fasilitas Publik</h2><div class="facility-grid"><a class="facility-card" href="/jenis-layanan-ptsp"><span class="facility-thumb"><img src="/images/berita/2026-briefing-ptsp-1.jpeg" alt="Ruang pelayanan PTSP Pengadilan Negeri Natuna" loading="lazy"></span><strong>Ruang PTSP</strong><span>Area layanan terpadu satu pintu.</span></a><a class="facility-card" href="/layanan-disabilitas"><span class="facility-thumb"><img src="/images/layanan/akses-disabilitas.jpg" alt="Guiding block jalur pemandu difabel di area layanan" loading="lazy"></span><strong>Akses Disabilitas</strong><span>Guiding block dan layanan prioritas difabel.</span></a><a class="facility-card" href="/posbakum"><span class="facility-thumb"><img src="/images/layanan/posbakum.jpg" alt="Informasi layanan Pos Bantuan Hukum" loading="lazy" style="object-position:center top"></span><strong>Posbakum</strong><span>Ruang bantuan hukum bagi masyarakat.</span></a><a class="facility-card" href="/kontak"><span class="facility-thumb"><img src="/images/sejarah/sejarah-pn-natuna.jpg" alt="Gedung Pengadilan Negeri Natuna" loading="lazy"></span><strong>Lokasi Kantor</strong><span>Alamat, peta, dan kanal kontak.</span></a></div>' WHERE id = 480;

UPDATE pnn_modules SET content = '<h2>Role Model PN Natuna</h2><div class="role-carousel role-cards" data-interval="6000" aria-label="Role model PN Natuna"><div class="role-carousel-viewport"><article class="role-slide is-active"><div class="role-card"><span class="role-card-badge">Role Model 2026</span><img src="/images/profil/pegawai/hakim/joko-ciptanto.jpg" alt="Joko Ciptanto, S.H., M.H." loading="lazy"><span class="role-card-meta"><span class="role-card-name">Joko Ciptanto, S.H., M.H.</span><span class="role-card-title">Wakil Ketua Pengadilan Negeri Natuna</span><span class="role-card-nip">NIP. 198006162008051001</span><span class="role-card-sk">SK KPT Kepulauan Riau No. 53/KPT.W.32.U/SK.KP3.4/IV/2026</span></span></div></article><article class="role-slide"><div class="role-card"><span class="role-card-badge">Agen Perubahan 2026</span><img src="/images/profil/pegawai/kepaniteraan/marihod.png" alt="Marihod Tua Lubis, S.H." loading="lazy"><span class="role-card-meta"><span class="role-card-name">Marihod Tua Lubis, S.H.</span><span class="role-card-title">Analis Perkara Peradilan</span><span class="role-card-nip">NIP. 200002282024051001</span><span class="role-card-sk">SK Ketua PN Natuna No. 126/KPN.W32-U4/SK.KP7.1/I/2026</span></span></div></article></div><div class="role-carousel-dots" aria-label="Pilih role model"><button type="button" data-role-slide="0" aria-label="Tampilkan Joko Ciptanto"></button><button type="button" data-role-slide="1" aria-label="Tampilkan Marihod Tua Lubis"></button></div></div>' WHERE id = 482;

UPDATE pnn_modules SET content = '<h2>Indeks Pelayanan Publik</h2><div class="survey-scores"><button type="button" class="survey-score-tile" data-maklumat-zoom="/images/surveys/SKM_TW2_2026.png" data-maklumat-label="Publikasi Indeks Kepuasan Masyarakat (SKM) — TW2 2026"><span class="survey-score-label">SKM / IKM</span><span class="survey-score-value">3,97 <em>/ 4,00</em></span><span class="survey-score-bar"><i style="--score-pct:99.27%"></i></span><span class="survey-score-meta">99,27% &middot; 61 responden</span></button><button type="button" class="survey-score-tile" data-maklumat-zoom="/images/surveys/IPAK_TW2_2026.png" data-maklumat-label="Publikasi Indeks Persepsi Anti Korupsi (IPAK) — TW2 2026"><span class="survey-score-label">IPAK</span><span class="survey-score-value">4,00 <em>/ 4,00</em></span><span class="survey-score-bar"><i style="--score-pct:100%"></i></span><span class="survey-score-meta">100,00% &middot; 61 responden</span></button></div><p class="survey-scores-note">Periode TW2 2026 (April&ndash;Juni). Klik kartu untuk membuka dokumen publikasi.</p>' WHERE id = 816;

UPDATE pnn_modules SET showtitle = 0 WHERE id = 810;

-- Band gelap Galeri Fasilitas via module class suffix (lebih kompatibel daripada :has())
UPDATE pnn_modules SET params = JSON_SET(params, '$.moduleclass_sfx', 'facility-band') WHERE id = 480;
