-- Retire long-cached profile photo URLs; only changed articles receive new lastmod.
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/pppk/ria.jpg','images/profil/pegawai/pppk/ria.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/pppk/ria.jpg','images/profil/pegawai/pppk/ria.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/pppk/ria.jpg','images/profil/pegawai/pppk/ria.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/pppk/ria.jpg%' OR `fulltext` LIKE '%images/profil/pegawai/pppk/ria.jpg%' OR `images` LIKE '%images/profil/pegawai/pppk/ria.jpg%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/pppk/ria.jpg','images/profil/pegawai/pppk/ria.webp') WHERE content LIKE '%images/profil/pegawai/pppk/ria.jpg%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/kepaniteraan/ari.png','images/profil/pegawai/kepaniteraan/ari.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/kepaniteraan/ari.png','images/profil/pegawai/kepaniteraan/ari.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/kepaniteraan/ari.png','images/profil/pegawai/kepaniteraan/ari.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/kepaniteraan/ari.png%' OR `fulltext` LIKE '%images/profil/pegawai/kepaniteraan/ari.png%' OR `images` LIKE '%images/profil/pegawai/kepaniteraan/ari.png%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/kepaniteraan/ari.png','images/profil/pegawai/kepaniteraan/ari.webp') WHERE content LIKE '%images/profil/pegawai/kepaniteraan/ari.png%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/kesekretariatan/juprizal.png','images/profil/pegawai/kesekretariatan/juprizal.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/kesekretariatan/juprizal.png','images/profil/pegawai/kesekretariatan/juprizal.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/kesekretariatan/juprizal.png','images/profil/pegawai/kesekretariatan/juprizal.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/kesekretariatan/juprizal.png%' OR `fulltext` LIKE '%images/profil/pegawai/kesekretariatan/juprizal.png%' OR `images` LIKE '%images/profil/pegawai/kesekretariatan/juprizal.png%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/kesekretariatan/juprizal.png','images/profil/pegawai/kesekretariatan/juprizal.webp') WHERE content LIKE '%images/profil/pegawai/kesekretariatan/juprizal.png%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/kepaniteraan/marihod.png','images/profil/pegawai/kepaniteraan/marihod.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/kepaniteraan/marihod.png','images/profil/pegawai/kepaniteraan/marihod.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/kepaniteraan/marihod.png','images/profil/pegawai/kepaniteraan/marihod.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/kepaniteraan/marihod.png%' OR `fulltext` LIKE '%images/profil/pegawai/kepaniteraan/marihod.png%' OR `images` LIKE '%images/profil/pegawai/kepaniteraan/marihod.png%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/kepaniteraan/marihod.png','images/profil/pegawai/kepaniteraan/marihod.webp') WHERE content LIKE '%images/profil/pegawai/kepaniteraan/marihod.png%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/pppk/ardiansyah.png','images/profil/pegawai/pppk/ardiansyah.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/pppk/ardiansyah.png','images/profil/pegawai/pppk/ardiansyah.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/pppk/ardiansyah.png','images/profil/pegawai/pppk/ardiansyah.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/pppk/ardiansyah.png%' OR `fulltext` LIKE '%images/profil/pegawai/pppk/ardiansyah.png%' OR `images` LIKE '%images/profil/pegawai/pppk/ardiansyah.png%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/pppk/ardiansyah.png','images/profil/pegawai/pppk/ardiansyah.webp') WHERE content LIKE '%images/profil/pegawai/pppk/ardiansyah.png%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/kesekretariatan/dion.png','images/profil/pegawai/kesekretariatan/dion.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/kesekretariatan/dion.png','images/profil/pegawai/kesekretariatan/dion.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/kesekretariatan/dion.png','images/profil/pegawai/kesekretariatan/dion.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/kesekretariatan/dion.png%' OR `fulltext` LIKE '%images/profil/pegawai/kesekretariatan/dion.png%' OR `images` LIKE '%images/profil/pegawai/kesekretariatan/dion.png%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/kesekretariatan/dion.png','images/profil/pegawai/kesekretariatan/dion.webp') WHERE content LIKE '%images/profil/pegawai/kesekretariatan/dion.png%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/kesekretariatan/mario.png','images/profil/pegawai/kesekretariatan/mario.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/kesekretariatan/mario.png','images/profil/pegawai/kesekretariatan/mario.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/kesekretariatan/mario.png','images/profil/pegawai/kesekretariatan/mario.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/kesekretariatan/mario.png%' OR `fulltext` LIKE '%images/profil/pegawai/kesekretariatan/mario.png%' OR `images` LIKE '%images/profil/pegawai/kesekretariatan/mario.png%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/kesekretariatan/mario.png','images/profil/pegawai/kesekretariatan/mario.webp') WHERE content LIKE '%images/profil/pegawai/kesekretariatan/mario.png%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/kesekretariatan/candra.jpeg','images/profil/pegawai/kesekretariatan/candra.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/kesekretariatan/candra.jpeg','images/profil/pegawai/kesekretariatan/candra.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/kesekretariatan/candra.jpeg','images/profil/pegawai/kesekretariatan/candra.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/kesekretariatan/candra.jpeg%' OR `fulltext` LIKE '%images/profil/pegawai/kesekretariatan/candra.jpeg%' OR `images` LIKE '%images/profil/pegawai/kesekretariatan/candra.jpeg%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/kesekretariatan/candra.jpeg','images/profil/pegawai/kesekretariatan/candra.webp') WHERE content LIKE '%images/profil/pegawai/kesekretariatan/candra.jpeg%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/pppk/yuningsih.png','images/profil/pegawai/pppk/yuningsih.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/pppk/yuningsih.png','images/profil/pegawai/pppk/yuningsih.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/pppk/yuningsih.png','images/profil/pegawai/pppk/yuningsih.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/pppk/yuningsih.png%' OR `fulltext` LIKE '%images/profil/pegawai/pppk/yuningsih.png%' OR `images` LIKE '%images/profil/pegawai/pppk/yuningsih.png%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/pppk/yuningsih.png','images/profil/pegawai/pppk/yuningsih.webp') WHERE content LIKE '%images/profil/pegawai/pppk/yuningsih.png%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/pppk/noki.jpg','images/profil/pegawai/pppk/noki.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/pppk/noki.jpg','images/profil/pegawai/pppk/noki.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/pppk/noki.jpg','images/profil/pegawai/pppk/noki.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/pppk/noki.jpg%' OR `fulltext` LIKE '%images/profil/pegawai/pppk/noki.jpg%' OR `images` LIKE '%images/profil/pegawai/pppk/noki.jpg%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/pppk/noki.jpg','images/profil/pegawai/pppk/noki.webp') WHERE content LIKE '%images/profil/pegawai/pppk/noki.jpg%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/kesekretariatan/faris.jpg','images/profil/pegawai/kesekretariatan/faris.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/kesekretariatan/faris.jpg','images/profil/pegawai/kesekretariatan/faris.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/kesekretariatan/faris.jpg','images/profil/pegawai/kesekretariatan/faris.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/kesekretariatan/faris.jpg%' OR `fulltext` LIKE '%images/profil/pegawai/kesekretariatan/faris.jpg%' OR `images` LIKE '%images/profil/pegawai/kesekretariatan/faris.jpg%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/kesekretariatan/faris.jpg','images/profil/pegawai/kesekretariatan/faris.webp') WHERE content LIKE '%images/profil/pegawai/kesekretariatan/faris.jpg%';
UPDATE #__content SET `introtext`=REPLACE(`introtext`,'images/profil/pegawai/pppk/kusnaidi.png','images/profil/pegawai/pppk/kusnaidi.webp'), `fulltext`=REPLACE(`fulltext`,'images/profil/pegawai/pppk/kusnaidi.png','images/profil/pegawai/pppk/kusnaidi.webp'), `images`=REPLACE(`images`,'images/profil/pegawai/pppk/kusnaidi.png','images/profil/pegawai/pppk/kusnaidi.webp'), modified=UTC_TIMESTAMP(), modified_by=0 WHERE `introtext` LIKE '%images/profil/pegawai/pppk/kusnaidi.png%' OR `fulltext` LIKE '%images/profil/pegawai/pppk/kusnaidi.png%' OR `images` LIKE '%images/profil/pegawai/pppk/kusnaidi.png%';
UPDATE #__modules SET content=REPLACE(content,'images/profil/pegawai/pppk/kusnaidi.png','images/profil/pegawai/pppk/kusnaidi.webp') WHERE content LIKE '%images/profil/pegawai/pppk/kusnaidi.png%';

-- Previous photo migration changed references without advancing article timestamps.
UPDATE #__content SET modified=UTC_TIMESTAMP(), modified_by=0 WHERE alias IN ('profil-hakim','profil-kepaniteraan','profil-kesekretariatan','kepaniteraan-pidana','kepaniteraan-perdata','kepaniteraan-hukum','kepaniteraan-khusus-perikanan','profil-pegawai-tidak-tetap','subbagian-ptip','subbagian-kepegawaian-ortala','subbagian-umum-keuangan','kata-sambutan') AND (modified IS NULL OR modified < '2026-09-25 00:00:00') AND (introtext LIKE '%images/profil/pegawai/pppk/ria.webp%' OR introtext LIKE '%images/profil/pegawai/kepaniteraan/ari.webp%' OR introtext LIKE '%images/profil/pegawai/kesekretariatan/juprizal.webp%' OR introtext LIKE '%images/profil/pegawai/kepaniteraan/marihod.webp%' OR introtext LIKE '%images/profil/pegawai/pppk/ardiansyah.webp%' OR introtext LIKE '%images/profil/pegawai/kesekretariatan/dion.webp%' OR introtext LIKE '%images/profil/pegawai/kesekretariatan/mario.webp%' OR introtext LIKE '%images/profil/pegawai/kesekretariatan/candra.webp%' OR introtext LIKE '%images/profil/pegawai/pppk/yuningsih.webp%' OR introtext LIKE '%images/profil/pegawai/pppk/noki.webp%' OR introtext LIKE '%images/profil/pegawai/kesekretariatan/faris.webp%' OR introtext LIKE '%images/profil/pegawai/pppk/kusnaidi.webp%');
