-- Publish fisheries registry staff and split each secretariat subdivision into responsible officer plus its own staff.
-- Cards are copied verbatim from the parent rosters; only the unit label of a cross-assigned card is restated for the page it appears on.

SET @anchor := '<section class="roster-section"><div class="roster-section-head"><h2>Ruang Lingkup Layanan</h2>';
SET @staff := '<section class="roster-section roster-section-staff"><div class="roster-section-head"><h2>Staf Kepaniteraan Khusus Perikanan</h2><span class="roster-count">2 orang</span></div><div class="roster-grid"><article class="roster-card"><div class="roster-photo"><img src="images/profil/pegawai/kesekretariatan/juprizal.png" alt="Juprizal, A.Md., A.B." loading="lazy"><span class="roster-degree">D3</span></div><div class="roster-body"><h3 class="roster-name">Juprizal, A.Md., A.B.</h3><div class="roster-role-row"><span class="roster-role">Dokumentalis Hukum</span><span class="roster-role">Kepaniteraan Khusus Perikanan</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>199510102025061005</dd></div><div><dt>Pangkat/Gol.</dt><dd>Pengatur / II.c</dd></div></dl></div></article><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/noki.jpg" alt="Noki Suryatno" loading="lazy"><span class="roster-degree">SMK</span></div><div class="roster-body"><h3 class="roster-name">Noki Suryatno</h3><div class="roster-role-row"><span class="roster-role">Kepaniteraan Khusus Perikanan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>199011052025211052</dd></div></dl></div></article></div></section>';
UPDATE #__content
SET introtext = REPLACE(introtext, @anchor, CONCAT(@staff, @anchor)),
    modified = UTC_TIMESTAMP(), modified_by = 0
WHERE alias = 'kepaniteraan-khusus-perikanan'
  AND introtext LIKE CONCAT('%', @anchor, '%')
  AND introtext NOT LIKE '%roster-section-staff%';

SET @old := '<section class="roster-section"><div class="roster-section-head"><h2>Penanggung Jawab</h2></div><div class="roster-grid"><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/kesekretariatan/candra.jpeg" alt="Candra Firmansyah, S.I.Pust." loading="lazy"><span class="roster-degree">S1</span></div><div class="roster-body"><h3 class="roster-name">Candra Firmansyah, S.I.Pust.</h3><span class="roster-role">Kasubbag Kepegawaian, Organisasi, dan Tata Laksana</span><dl class="roster-meta"><div><dt>NIP</dt><dd>199312102020121001</dd></div><div><dt>Pangkat/Gol.</dt><dd>Penata Muda / III.a</dd></div></dl></div></article><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/noki.jpg" alt="Noki Suryatno" loading="lazy"><span class="roster-degree">SMK</span></div><div class="roster-body"><h3 class="roster-name">Noki Suryatno</h3><div class="roster-role-row"><span class="roster-role">Subbag Kepegawaian, Organisasi, dan Tata Laksana</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>199011052025211052</dd></div></dl></div></article></div></section>';
SET @new := '<section class="roster-section"><div class="roster-section-head"><h2>Penanggung Jawab</h2></div><div class="roster-grid"><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/kesekretariatan/candra.jpeg" alt="Candra Firmansyah, S.I.Pust." loading="lazy"><span class="roster-degree">S1</span></div><div class="roster-body"><h3 class="roster-name">Candra Firmansyah, S.I.Pust.</h3><span class="roster-role">Kasubbag Kepegawaian, Organisasi, dan Tata Laksana</span><dl class="roster-meta"><div><dt>NIP</dt><dd>199312102020121001</dd></div><div><dt>Pangkat/Gol.</dt><dd>Penata Muda / III.a</dd></div></dl></div></article></div></section><section class="roster-section roster-section-staff"><div class="roster-section-head"><h2>Staf Subbagian Kepegawaian, Organisasi, dan Tata Laksana</h2><span class="roster-count">1 orang</span></div><div class="roster-grid"><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/noki.jpg" alt="Noki Suryatno" loading="lazy"><span class="roster-degree">SMK</span></div><div class="roster-body"><h3 class="roster-name">Noki Suryatno</h3><div class="roster-role-row"><span class="roster-role">Subbag Kepegawaian, Organisasi, dan Tata Laksana</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>199011052025211052</dd></div></dl></div></article></div></section>';
UPDATE #__content
SET introtext = REPLACE(introtext, @old, @new),
    modified = UTC_TIMESTAMP(), modified_by = 0
WHERE alias = 'subbagian-kepegawaian-ortala'
  AND introtext LIKE CONCAT('%', @old, '%')
  AND introtext NOT LIKE '%roster-section-staff%';

SET @old := '<section class="roster-section"><div class="roster-section-head"><h2>Penanggung Jawab</h2></div><div class="roster-grid"><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/kesekretariatan/faris.jpg" alt="Muhammad Faris Akbar, A.Md." loading="lazy"><span class="roster-degree">D3</span></div><div class="roster-body"><h3 class="roster-name">Muhammad Faris Akbar, A.Md.</h3><span class="roster-role">Plt. Kasubbag Perencanaan, Teknologi Informasi, dan Pelaporan</span><dl class="roster-meta"><div><dt>NIP</dt><dd>199412162025061006</dd></div><div><dt>Pangkat/Gol.</dt><dd>Pengatur / II.c</dd></div></dl></div></article><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/bait.png" alt="Bait, S.H." loading="lazy"><span class="roster-degree">S1</span></div><div class="roster-body"><h3 class="roster-name">Bait, S.H.</h3><div class="roster-role-row"><span class="roster-role">Subbag Perencanaan, TI, dan Pelaporan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>199005052025211076</dd></div></dl></div></article></div></section>';
SET @new := '<section class="roster-section"><div class="roster-section-head"><h2>Penanggung Jawab</h2></div><div class="roster-grid"><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/kesekretariatan/faris.jpg" alt="Muhammad Faris Akbar, A.Md." loading="lazy"><span class="roster-degree">D3</span></div><div class="roster-body"><h3 class="roster-name">Muhammad Faris Akbar, A.Md.</h3><span class="roster-role">Plt. Kasubbag Perencanaan, Teknologi Informasi, dan Pelaporan</span><dl class="roster-meta"><div><dt>NIP</dt><dd>199412162025061006</dd></div><div><dt>Pangkat/Gol.</dt><dd>Pengatur / II.c</dd></div></dl></div></article></div></section><section class="roster-section roster-section-staff"><div class="roster-section-head"><h2>Staf Subbagian Perencanaan, TI, dan Pelaporan</h2><span class="roster-count">1 orang</span></div><div class="roster-grid"><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/bait.png" alt="Bait, S.H." loading="lazy"><span class="roster-degree">S1</span></div><div class="roster-body"><h3 class="roster-name">Bait, S.H.</h3><div class="roster-role-row"><span class="roster-role">Subbag Perencanaan, TI, dan Pelaporan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>199005052025211076</dd></div></dl></div></article></div></section>';
UPDATE #__content
SET introtext = REPLACE(introtext, @old, @new),
    modified = UTC_TIMESTAMP(), modified_by = 0
WHERE alias = 'subbagian-ptip'
  AND introtext LIKE CONCAT('%', @old, '%')
  AND introtext NOT LIKE '%roster-section-staff%';

SET @old := '<section class="roster-section"><div class="roster-section-head"><h2>Penanggung Jawab</h2></div><div class="roster-grid"><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/kesekretariatan/frans.jpg" alt="Frans Alberto Siregar, S.T." loading="lazy"><span class="roster-degree">S1</span></div><div class="roster-body"><h3 class="roster-name">Frans Alberto Siregar, S.T.</h3><span class="roster-role">Plt. Kasubbag Umum dan Keuangan</span><dl class="roster-meta"><div><dt>NIP</dt><dd>199808202025061008</dd></div><div><dt>Pangkat/Gol.</dt><dd>Penata Muda / III.a</dd></div></dl></div></article><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/ratih.png" alt="Rati Pusita, S.Pd.I." loading="lazy"><span class="roster-degree">S1</span></div><div class="roster-body"><h3 class="roster-name">Rati Pusita, S.Pd.I.</h3><div class="roster-role-row"><span class="roster-role">Subbag Umum dan Keuangan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>198610172025212030</dd></div></dl></div></article><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/ria.jpg" alt="Ria Angelina Sitompul" loading="lazy"><span class="roster-degree">SMA</span></div><div class="roster-body"><h3 class="roster-name">Ria Angelina Sitompul</h3><div class="roster-role-row"><span class="roster-role">Subbag Umum dan Keuangan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>199007292025212038</dd></div></dl></div></article><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/riko.png" alt="Riko Gustianto" loading="lazy"><span class="roster-degree">MA</span></div><div class="roster-body"><h3 class="roster-name">Riko Gustianto</h3><div class="roster-role-row"><span class="roster-role">Subbag Umum dan Keuangan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>200003232025211015</dd></div></dl></div></article><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/kusnaidi.png" alt="Kusnaidi" loading="lazy"><span class="roster-degree">SMA</span></div><div class="roster-body"><h3 class="roster-name">Kusnaidi</h3><div class="roster-role-row"><span class="roster-role">Subbag Umum dan Keuangan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>199011202025211033</dd></div></dl></div></article></div></section>';
SET @new := '<section class="roster-section"><div class="roster-section-head"><h2>Penanggung Jawab</h2></div><div class="roster-grid"><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/kesekretariatan/frans.jpg" alt="Frans Alberto Siregar, S.T." loading="lazy"><span class="roster-degree">S1</span></div><div class="roster-body"><h3 class="roster-name">Frans Alberto Siregar, S.T.</h3><span class="roster-role">Plt. Kasubbag Umum dan Keuangan</span><dl class="roster-meta"><div><dt>NIP</dt><dd>199808202025061008</dd></div><div><dt>Pangkat/Gol.</dt><dd>Penata Muda / III.a</dd></div></dl></div></article></div></section><section class="roster-section roster-section-staff"><div class="roster-section-head"><h2>Staf Subbagian Umum dan Keuangan</h2><span class="roster-count">4 orang</span></div><div class="roster-grid"><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/ratih.png" alt="Rati Pusita, S.Pd.I." loading="lazy"><span class="roster-degree">S1</span></div><div class="roster-body"><h3 class="roster-name">Rati Pusita, S.Pd.I.</h3><div class="roster-role-row"><span class="roster-role">Subbag Umum dan Keuangan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>198610172025212030</dd></div></dl></div></article><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/ria.jpg" alt="Ria Angelina Sitompul" loading="lazy"><span class="roster-degree">SMA</span></div><div class="roster-body"><h3 class="roster-name">Ria Angelina Sitompul</h3><div class="roster-role-row"><span class="roster-role">Subbag Umum dan Keuangan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>199007292025212038</dd></div></dl></div></article><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/riko.png" alt="Riko Gustianto" loading="lazy"><span class="roster-degree">MA</span></div><div class="roster-body"><h3 class="roster-name">Riko Gustianto</h3><div class="roster-role-row"><span class="roster-role">Subbag Umum dan Keuangan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>200003232025211015</dd></div></dl></div></article><article class="roster-card"><div class="roster-photo"><img src="/images/profil/pegawai/pppk/kusnaidi.png" alt="Kusnaidi" loading="lazy"><span class="roster-degree">SMA</span></div><div class="roster-body"><h3 class="roster-name">Kusnaidi</h3><div class="roster-role-row"><span class="roster-role">Subbag Umum dan Keuangan</span><span class="roster-role">PPPK</span></div><dl class="roster-meta"><div><dt>NIP</dt><dd>199011202025211033</dd></div></dl></div></article></div></section>';
UPDATE #__content
SET introtext = REPLACE(introtext, @old, @new),
    modified = UTC_TIMESTAMP(), modified_by = 0
WHERE alias = 'subbagian-umum-keuangan'
  AND introtext LIKE CONCAT('%', @old, '%')
  AND introtext NOT LIKE '%roster-section-staff%';
