<?php
/** CSP hashes only code registered through Joomla's trusted script renderer, never page content. */
\defined('_JEXEC') or die;

function pnNatunaContentSecurityPolicy(string $registeredScripts, bool $https): string
{
    $hashes = [];
    // This input is generated by ScriptsRenderer, not article/module HTML. Preserve exact script bytes.
    preg_match_all('~<script\b[^>]*>(.*?)</script\s*>~is', $registeredScripts, $matches);
    foreach ($matches[1] as $source) {
        $source = str_replace(["\r\n", "\r"], "\n", $source);
        if ($source === '') {
            continue;
        }
        $hashes["'sha256-" . base64_encode(hash('sha256', $source, true)) . "'"] = true;
    }
    return "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; "
        . "form-action 'self' https://www.google.com; script-src 'self' https://challenges.cloudflare.com https://www.instagram.com "
        . implode(' ', array_keys($hashes)) . "; script-src-attr 'none'; "
        . "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; "
        . "font-src 'self' data: https://fonts.gstatic.com; frame-src 'self' https://challenges.cloudflare.com https://www.google.com https://www.instagram.com https://www.youtube-nocookie.com; "
        . "connect-src 'self' https://www.instagram.com; media-src 'self'; worker-src 'self' blob:"
        . ($https ? '; upgrade-insecure-requests' : '');
}

function pnNatunaRegisterCsp($app): void
{
    // Native HTTP Headers only hashes legacy head declarations, missing WAM/importmaps.
    // Stable hashes are stored with cached HTML/headers; no reusable per-response nonce.
    $app->getDispatcher()->addListener('onBeforeRespond', static function () use ($app): void {
        $document = $app->getDocument();
        if ($document->getType() !== 'html') {
            return;
        }
        $renderer = new \Joomla\CMS\Document\Renderer\Html\ScriptsRenderer($document);
        $app->setHeader('Content-Security-Policy', pnNatunaContentSecurityPolicy(
            $renderer->render(null),
            \Joomla\CMS\Uri\Uri::getInstance()->isSsl()
        ), true);
    }, PHP_INT_MIN);
}
