<?php
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
require_once __DIR__ . '/../templates/pn_natuna_2026/instagram-feed.php';
function ig_log(string $message): void { $dir = dirname(__DIR__) . '/logs'; if (!is_dir($dir)) @mkdir($dir, 0700, true); @file_put_contents($dir . '/instagram-refresh.log', '[' . gmdate('c') . '] ' . $message . "\n", FILE_APPEND | LOCK_EX); }
function ig_env(): array { $file = getenv('INSTAGRAM_ENV_FILE') ?: dirname(__DIR__) . '/.instagram-rss.env'; if (!is_file($file)) return []; $out=[]; foreach (file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [] as $line) { if (preg_match('/^\s*([A-Z_]+)=(.*)$/', $line, $m)) $out[$m[1]] = trim($m[2], " \t\"'"); } return $out; }
function ig_get(string $url, int $limit, string $accept): ?string { $ch=curl_init($url); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>15,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_HTTPHEADER=>['Accept: '.$accept,'User-Agent: PN-Natuna-Instagram-Cache/1.0'],CURLOPT_HEADER=>true]); $raw=curl_exec($ch); $code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE); $size=(int)curl_getinfo($ch,CURLINFO_SIZE_DOWNLOAD); $header=(int)curl_getinfo($ch,CURLINFO_HEADER_SIZE); curl_close($ch); if (!is_string($raw)||$code!==200||$size<1||$size>$limit) return null; return substr($raw,$header); }
$env = ig_env(); $url = getenv('INSTAGRAM_RSS_URL') ?: ($env['INSTAGRAM_RSS_URL'] ?? ''); $p=parse_url($url); if (($p['scheme'] ?? '') !== 'https' || strtolower($p['host'] ?? '') !== 'rss.app') { ig_log('refresh rejected: invalid configured feed host'); exit(2); }
if (!function_exists('curl_init')) { ig_log('refresh failed: curl unavailable'); exit(3); }
$rss=ig_get($url,2097152,'application/rss+xml, application/xml;q=0.9'); $parsed=is_string($rss)?pn_natuna_instagram_parse_rss($rss):[]; if (!$parsed) { ig_log('refresh failed: no valid RSS posts'); exit(4); }
$root=dirname(__DIR__); $media=$root.'/media/instagram'; $cache=$root.'/cache/pn_natuna_instagram'; if (!is_dir($media)) @mkdir($media,0755,true); $items=[];
foreach ($parsed as $post) { $binary=ig_get($post['thumbnail'],8388608,'image/avif,image/webp,image/jpeg,image/png'); if (!is_string($binary)) continue; $info=@getimagesizefromstring($binary); $mime=(new finfo(FILEINFO_MIME_TYPE))->buffer($binary); if (!$info || !in_array($mime,['image/jpeg','image/png','image/webp'],true) || $info[0]<1 || $info[1]<1 || $info[0]>12000 || $info[1]>12000) continue; $source=@imagecreatefromstring($binary); if (!$source || !function_exists('imagewebp')) continue; $w=imagesx($source); $h=imagesy($source); if ($w>1080 || $h>1080) { $scale=min(1080/$w,1080/$h); $nw=max(1,(int)round($w*$scale)); $nh=max(1,(int)round($h*$scale)); $dst=imagecreatetruecolor($nw,$nh); imagecopyresampled($dst,$source,0,0,0,0,$nw,$nh,$w,$h); imagedestroy($source); $source=$dst; $w=$nw; $h=$nh; } $name=hash('sha256',$post['guid']).'.webp'; $tmp=$media.'/.'.$name.'.'.bin2hex(random_bytes(4)).'.tmp'; if (!@imagewebp($source,$tmp,82)) { imagedestroy($source); @unlink($tmp); continue; } imagedestroy($source); if (!@rename($tmp,$media.'/'.$name)) { @unlink($tmp); continue; } $items[]=['permalink'=>$post['permalink'],'caption'=>$post['caption'],'date'=>$post['date'],'image'=>'/media/instagram/'.$name,'width'=>$w,'height'=>$h]; }
$sourceBuildDate = gmdate(DATE_ATOM); libxml_use_internal_errors(true); $source = @simplexml_load_string($rss, 'SimpleXMLElement', LIBXML_NONET | LIBXML_NOCDATA); if ($source && isset($source->channel->lastBuildDate)) { $parsedDate = strtotime((string) $source->channel->lastBuildDate); if ($parsedDate !== false) $sourceBuildDate = gmdate(DATE_ATOM, $parsedDate); } if (!$items || !pn_natuna_instagram_promote_cache($cache,['updated_at'=>gmdate(DATE_ATOM),'source_build_date'=>$sourceBuildDate,'items'=>$items])) { ig_log('refresh failed: no safe image set; prior cache retained'); exit(5); } ig_log('refresh succeeded: '.count($items).' posts'); exit(0);
