<?php
$root=dirname(__DIR__);$index=file_get_contents($root.'/templates/pn_natuna_2026/index.php');$hero=file_get_contents($root.'/templates/pn_natuna_2026/hero-slider.php');$js=file_get_contents($root.'/templates/pn_natuna_2026/js/template.js');$css=file_get_contents($root.'/templates/pn_natuna_2026/css/template.css');$f=[];$e=static function($c,$m)use(&$f){if(!$c)$f[]=$m;};
$e(str_contains($index,'data-mobile-menu-filter'),'Mobile menu filter input missing.');
$e(str_contains($index,'data-mobile-menu-empty'),'Mobile menu empty state missing.');
$e(str_contains($index,'data-sidebar-rail-status'),'Sidebar rail status missing.');
$e(str_contains($hero,'hero-pledge__poster'),'Tombol poster penuh Zona Integritas hilang.');
$e(str_contains($hero,'data-youtube-count'),'YouTube count status missing.');
$e(str_contains($js,'setupMobileMenuFilter'),'Mobile menu filtering behavior missing.');
$e(str_contains($js,"window.scrollY > 900"),'Back-to-top threshold must be 900px.');
$e(!str_contains($js,'prefetchIntegrityPoster'),'Secondary integrity poster must not be idle-prefetched.');
$e(!str_contains($js,'setupHeroPrefetch'),'Hero secondary media must not compete with the active LCP image.');
$e(str_contains($js,'setupMobileRailStatus'),'Rail status behavior missing.');
$e((bool)preg_match('/@media \(max-width:\s*760px\).*?\.quick-links\s*\{[^}]*display:\s*none/s',$css),'Duplicate mobile quick-links must be hidden.');
$e((bool)preg_match('/body\.is-home \.floating-whatsapp\s*\{[^}]*display:\s*none/s',$css),'Homepage mobile WhatsApp float must be hidden.');
$e(!str_contains($css, '.youtube-showcase-rail > li:nth-child(n+4)'),'Mobile YouTube rail must keep all five items available.');
$e(!str_contains($js, "item.closest('li').hidden = mobile && index >= 3"),'Mobile rail must not hide the fourth and fifth items.');
$e((bool)preg_match('/\.youtube-showcase-rail > li\s*\{[^}]*flex:\s*0 0 calc\(100% - 34px\);[^}]*width:\s*auto;/s',$css),'Mobile rail items must own a non-overlapping flex basis.');
$e(str_contains($css,'.mobile-rail-hint'),'Mobile rail hint styles missing.');
$e((bool)preg_match('/\.home-juknis-sidebar\s*\{[^}]*position:\s*relative;[^}]*align-items:\s*flex-start;/s',$css),'Sidebar rail must keep cards at natural height.');
$e((bool)preg_match('/\.home-juknis-sidebar > \.mobile-rail-status\s*\{[^}]*position:\s*absolute;/s',$css),'Sidebar rail status must not participate as a flex card.');
$e((bool)preg_match('/body\.is-home \.back-to-top\s*\{[^}]*right:\s*max\(12px, env\(safe-area-inset-right\)\);/s',$css),'Mobile back-to-top must remain fully inside the viewport.');
$e(str_contains($index,'menu-toggle__icon'),'Mobile menu button needs a hamburger icon.');
$e((bool)preg_match('/\.site-header\s*\{[^}]*height:\s*68px;/s',$css),'Mobile header must use compact 68px height.');
$e((bool)preg_match('/\.header-brand\s*\{[^}]*height:\s*68px;[^}]*padding:\s*8px 68px 8px 12px;/s',$css),'Mobile brand row must use compact grid spacing.');
$e((bool)preg_match('/\.brand-mark\s*\{[^}]*width:\s*42px;[^}]*height:\s*42px;/s',$css),'Mobile logo must be 42px.');
$e((bool)preg_match('/\.menu-toggle\s*\{[^}]*width:\s*48px;[^}]*height:\s*48px;/s',$css),'Mobile menu control must be a 48px square.');
$e((bool)preg_match('/\.announcement-showcase__actions\s*\{[^}]*justify-content:\s*center;/s',$css),'Announcement action group must be centered on mobile.');
$e((bool)preg_match('/\.instansi-tabbar\s*\{[^}]*justify-content:\s*center;/s',$css),'Tabbar instansi harus terpusat sebagai grup aksi di mobile.');
$e(str_contains($css,'.section-action { display: inline-flex; min-height: 48px; align-items: center; justify-content: center; padding: 10px 16px; line-height: 1.2; text-align: center; }'),'Mobile section-action pills must center their content internally.');
$e(str_contains($css,'scrollbar-width: none'),'Mobile rail scrollbar suppression missing.');
$e(str_contains($css,'font-size: .68rem'),'Bottom navigation font floor missing.');
$e(str_contains($css,'@media (hover: none)'),'Touch active feedback missing.');
$e(str_contains($css,'font-size: 200%'),'200 percent text zoom guard missing.');
if($f){fwrite(STDERR,implode(PHP_EOL,$f).PHP_EOL);exit(1);}echo "comprehensive mobile polish contract: ok\n";
